#!/bin/sh

set -e

# git clone
cd /var/www/shinage-player
git fetch --all
git reset --hard origin/master

# cleanup old site definitions
rm -rf /etc/nginx/sites-enabled/*

# install nginx configuration
mkdir -p /etc/nginx/conf.d/
cp -f /var/www/shinage-player/nginx/diagnostic-htpasswd /etc/nginx/conf.d/diagnostic-htpasswd
cp -f /var/www/shinage-player/nginx/site-signage /etc/nginx/sites-enabled/site-signage


#TODO? restart nginx ?

