#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac


# run actual configuration
export LH_LANGUAGE="de"
lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
    --distribution jessie \
    --archive-areas "main contrib non-free" \
	--linux-packages "linux-image linux-headers" \
    --bootappend-live "boot=live components quiet splash persistence locales=de_DE.UTF-8 keyboard-layouts=de keymap=de keyb=de vga=791" \
    "${@}"

