#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac


# copy skeleton data
PLAYER_PATH=../shinage-player

mkdir -p config/includes.chroot/var/www
cp -r $PLAYER_PATH/www/* ./config/includes.chroot/var/www/

mkdir -p config/includes.chroot/etc/nginx/sites-enabled
mkdir -p config/includes.chroot/etc/nginx/conf.d
cp -r $PLAYER_PATH/nginx/site-diagnostics ./config/includes.chroot/etc/nginx/sites-enabled/
cp -r $PLAYER_PATH/nginx/site-signage ./config/includes.chroot/etc/nginx/sites-enabled/
cp -r $PLAYER_PATH/nginx/diagnostic-htpasswd ./config/includes.chroot/etc/nginx/conf.d/


# run actual configuration
export LH_LANGUAGE="de"
lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--linux-packages "linux-image linux-headers" \
    --bootappend-live "boot=live components quiet splash persistence locales=de_DE.UTF-8 keyboard-layouts=de keymap=de keyb=de vga=791" \
    "${@}"

